### ISSUE TITLE
Big next step: Multiplayer

### ISSUE THREAD

**Issue by levithomason** [Lou-Saydus/ticTacToe#5]
https://firebase.google.com offers free real time data storage and syncing.  It would be awesome to have an online multiplayer experience 😄 

You could browse to:

https://lou-saydus.github.io/ticTacToe/#<room-name\>

Where `<room-name>` is any string you want.  When the page loads, cou would create an object in firebase at `<room-name>` which stores the game data:

https://\<your-app\>.firebase.io/#<room-name\>
```js
{
  players: 0,
  turn: 'x',
  board: [
    [null, null, null],
    [null, null, null],
    [null, null, null],
  ]
}
```

The first person to arrive would be allowed to make a turn on X's and the second person to load the room would be allowed to play on Os.  Anyone else loading the room would just be watching.

- [x] Add database initialization
- [x] Add lobby/session unique ID support
- [x] Add basic User Name support
- [x] Add game/board state tracking 
- [x] Add basic observer support

**Comment by HudsonMercer** [comment]
Full multiplayer support added with support for observers and names. Minor features still missing but majority of functionality is there.

**Comment by levithomason** [comment]
What?! Awesome man, we should get on hero and make some final tweaks and talk about lessons learned.
